{{- if and .Values.karpenter.enabled .Values.karpenter.ec2NodeClass.enabled }}
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ .Values.karpenter.ec2NodeClass.name }}
  labels:
    {{- include "runs-fleet.labels" . | nindent 4 }}
spec:
  amiFamily: {{ .Values.karpenter.ec2NodeClass.amiFamily }}
  {{- if .Values.karpenter.ec2NodeClass.amiSelectorTerms }}
  amiSelectorTerms:
    {{- toYaml .Values.karpenter.ec2NodeClass.amiSelectorTerms | nindent 4 }}
  {{- end }}
  instanceProfile: {{ .Values.karpenter.ec2NodeClass.instanceProfile }}
  subnetSelectorTerms:
    {{- toYaml .Values.karpenter.ec2NodeClass.subnetSelectorTerms | nindent 4 }}
  securityGroupSelectorTerms:
    {{- toYaml .Values.karpenter.ec2NodeClass.securityGroupSelectorTerms | nindent 4 }}
  {{- with .Values.karpenter.ec2NodeClass.blockDeviceMappings }}
  blockDeviceMappings:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.karpenter.ec2NodeClass.metadataOptions }}
  metadataOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.karpenter.ec2NodeClass.userData }}
  userData: |
    {{- .Values.karpenter.ec2NodeClass.userData | nindent 4 }}
  {{- end }}
{{- end }}
