apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "runs-fleet.runner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runs-fleet.runner.labels" . | nindent 4 }}
