name: Rami Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissinos:
  pull-requests: write
  content: read

jobs:
  review:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    steps:
      - uses: Shavakan/rami-actions@v1
        with:
          api_endpoint: ${{ secrets.RAMI_API_ENDPOINT }}
